fix yang connector gnmi reconnect
CiscoTestAutomation/yang pull request #111
Opened 2023-11-28 16:53 UTC by xvincent

2023-11-28 19:13 UTC, ThomasJRyan requested changes
Seems functional to me. Needs a changelog and likely a untitest to go with it though

2023-11-29 11:13 UTC, xvincent commented on connector/src/yang/connector/gnmi.py
> +        """Helper method to keep backwrads compatibility.
fixed in 017b3f4

2023-11-29 11:13 UTC, xvincent commented on connector/src/yang/connector/gnmi.py
> +        print(f'XAV001: self.dev_args  = {self.dev_args}')
removed in a865ce5

2023-11-29 11:14 UTC, xvincent commented on connector/src/yang/connector/gnmi.py
> +        print('XAV002: really connect in def connect()')
removed print in a865ce5

2023-11-29 17:33 UTC, miott commented
Add a detailed description for this pull request please (and a changelog).

2023-12-04 09:40 UTC, xvincent commented
@miott , I added the changelog december.rst. Can you please this is correct.
Is there anything else I can do on my side ?

2023-12-04 16:40 UTC, miott commented
> @miott , I added the changelog december.rst. Can you please this is correct. Is there anything else I can do on my side ?

I approved this pull request 5 days ago.  You need another approval.

2023-12-06 02:37 UTC, ThomasJRyan requested changes

2023-12-06 02:37 UTC, ThomasJRyan commented on connector/docs/changelog/2023/december.rst
My apologies for this, but the changelog should go here https://github.com/CiscoTestAutomation/yang/tree/master/connector/docs/changelog/undistributed

We have a template in there for you to follow. Add it there and request a re-review from me

2023-12-06 09:22 UTC, xvincent commented on connector/docs/changelog/2023/december.rst
@ThomasJRyan , I updated, added new changelog undistributed: fix_gnmi_reconnect.rst

2023-12-07 16:10 UTC, ThomasJRyan approved these changes

2023-12-07 16:11 UTC, merged