Tahigash ncdiff sync
CiscoTestAutomation/yang pull request #113
Opened 2023-12-03 03:28 UTC by tahigash

2024-02-06 17:00 UTC, Taarini approved these changes

2024-02-08 21:53 UTC, dwapstra commented on connector/src/yang/connector/netconf.py
> +            timeout will use self.timeout.
```suggestion
            default value is 30 seconds. If timeout is less than 30, 
            timeout will use the default of 30 seconds.
```

2024-02-08 21:54 UTC, dwapstra commented on ncdiff/docs/changelog/2024/February.rst
Changelog should go into connector/docs/changelog/undistributed, the february file is created as part of the release process.

2024-02-08 21:55 UTC, dwapstra requested changes
Code looks fine, please update docs as commented.

2024-02-08 22:19 UTC, tahigash commented on ncdiff/docs/changelog/2024/February.rst
addressed!

2024-02-08 22:32 UTC, dwapstra approved these changes

2024-02-08 22:41 UTC, merged