Update protofiles + unpin protobuf dependency
CiscoTestAutomation/yang pull request #92
Opened 2023-06-08 15:49 UTC by GerriorL

Newer versions of python require a newer protobuf version which requires the regeneration of proto files

2023-06-08 16:15 UTC, miott7 approved these changes

2023-06-08 16:16 UTC, miott7 reviewed
Sanity tests failing?

2023-06-11 18:39 UTC, dwapstra requested changes
Please add changelog

2023-06-16 19:33 UTC, bastell approved these changes

2023-06-19 03:39 UTC, dwapstra approved these changes

2023-06-19 14:40 UTC, merged